# Generated by Django 4.2.1 on 2023-10-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('chip', 'project_name', 'version', 'idf_version', 'sha256_hash')},
        ),
        migrations.AddField(
            model_name='meshnode',
            name='firmware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_on', to='mesh.firmware', verbose_name='firmware'),
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='compile_time',
        ),
    ]
