# Generated by Django 4.2.1 on 2023-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0002_alter_firmware_unique_together_meshnode_firmware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshnode',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='name'),
        ),
    ]
