# Generated by Django 5.0.1 on 2024-03-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0013_meshnode_upstream_alter_nodemessage_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshnode',
            name='name',
        ),
    ]
