# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 14:14
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site', '0001_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, verbose_name='Text'),
        ),
    ]
