# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_announcement_tweaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
