# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_siteupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteupdate',
            options={'get_latest_by': 'created', 'verbose_name': 'Site update', 'verbose_name_plural': 'Site updates'},
        ),
    ]
