# Generated by Django 2.1.4 on 2018-12-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_siteupdate_tweaks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteupdate',
            options={'default_related_name': 'siteupdates', 'get_latest_by': 'created', 'verbose_name': 'Site update', 'verbose_name_plural': 'Site updates'},
        ),
    ]
