# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20170612_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['created', 'pk'], 'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AddField(
            model_name='changeset',
            name='session_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
