# Generated by Django 4.2.7 on 2023-12-20 22:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_django_4_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedobject',
            name='updated_fields',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='updated fields'),
        ),
    ]
