# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20170618_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='deletes_change',
        ),
        migrations.AddField(
            model_name='change',
            name='discarded_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discards', to='editor.Change', verbose_name='discarded by other change'),
        ),
        migrations.AlterField(
            model_name='change',
            name='action',
            field=models.CharField(choices=[('create', 'create object'), ('delete', 'delete object'), ('update', 'update attribute'), ('m2m_add', 'add many to many relation'), ('m2m_remove', 'add many to many relation')], max_length=16, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='change',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='model name'),
        ),
    ]
