# Generated by Django 5.0.8 on 2024-09-26 10:06

import c3nav.editor.changes
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_changedobject_json_encoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='last_cleaned_with',
        ),
        migrations.AddField(
            model_name='changeset',
            name='changes',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=c3nav.editor.changes.ChangedObjectCollection, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=c3nav.editor.changes.ChangedObjectCollection),
        ),
        migrations.DeleteModel(
            name='ChangedObject',
        ),
    ]
