# Generated by Django 5.0.8 on 2024-08-22 17:03
import c3nav.editor.changes
import c3nav.editor.models.changeset
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations

import c3nav.editor.changes


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_changedobject_json_encoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='last_cleaned_with',
        ),
        migrations.AddField(
            model_name='changeset',
            name='changes',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=c3nav.editor.changes.ChangeSetChanges, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=c3nav.editor.changes.ChangeSetChanges),
        ),
        migrations.DeleteModel(
            name='ChangedObject',
        ),
    ]
