# Generated by Django 5.0.8 on 2024-12-15 14:33

import c3nav.editor.changes
import c3nav.editor.models.changeset
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_changeset_rewrite_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='changes',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=c3nav.editor.models.changeset._changed_object_collection_default, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=c3nav.editor.changes.ChangedObjectCollection),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
    ]
