# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20170627_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changedobject',
            options={'base_manager_name': 'objects', 'ordering': ['created', 'pk'], 'verbose_name': 'Changed object', 'verbose_name_plural': 'Changed objects'},
        ),
        migrations.AddField(
            model_name='changedobject',
            name='stale',
            field=models.BooleanField(default=False, verbose_name='stale'),
        ),
        migrations.AlterField(
            model_name='changedobject',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='object was deleted'),
        ),
    ]
