# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20170629_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
