# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0007_auto_20170629_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='applied_by',
        ),
        migrations.AddField(
            model_name='changeset',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_changesets', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
    ]
