# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20170629_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='proposed',
        ),
        migrations.AddField(
            model_name='changeset',
            name='state',
            field=models.CharField(choices=[('unproposed', 'unproposed'), ('proposed', 'proposed'), ('review', 'in review'), ('rejected', 'rejected'), ('finallyrejected', 'finally rejected'), ('applied', 'accepted')], default='unproposed', max_length=20),
        ),
    ]
