# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20170704_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='session_id',
        ),
    ]
