# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_changeset_last_state_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changesetupdate',
            name='author',
        ),
        migrations.AlterField(
            model_name='changeset',
            name='state',
            field=models.CharField(choices=[('unproposed', 'unproposed'), ('proposed', 'proposed'), ('review', 'in review'), ('rejected', 'rejected'), ('reproposed', 'proposed again'), ('finallyrejected', 'finally rejected'), ('applied', 'accepted and applied')], db_index=True, default='unproposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='changesetupdate',
            name='state',
            field=models.CharField(choices=[('unproposed', 'unproposed'), ('proposed', 'proposed'), ('review', 'in review'), ('rejected', 'rejected'), ('reproposed', 'proposed again'), ('finallyrejected', 'finally rejected'), ('applied', 'accepted and applied')], db_index=True, max_length=20, null=None),
        ),
    ]
