# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0014_mapupdate'),
        ('editor', '0016_auto_20170705_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='map_update',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changeset', to='mapdata.MapUpdate', verbose_name='map update'),
        ),
    ]
