# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0018_auto_20170708_1752'),
        ('editor', '0017_changeset_map_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='last_cleaned_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_changesets', to='mapdata.MapUpdate'),
        ),
    ]
