# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_changeset_last_cleaned_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'permissions': (('review_changeset', 'Can review change sets'), ('direct_edit', 'Can use direct edit')), 'verbose_name': 'Change Set', 'verbose_name_plural': 'Change Sets'},
        ),
    ]
