# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'verbose_name': 'Change Set', 'verbose_name_plural': 'Change Sets'},
        ),
    ]
