# Generated by Django 2.1.1 on 2018-09-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0020_remove_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='last_cleaned_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_changesets', to='mapdata.MapUpdate'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='map_update',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changeset', to='mapdata.MapUpdate', verbose_name='map update'),
        ),
    ]
