# Generated by Django 4.0.3 on 2022-04-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routing', '0001_routeoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeoptions',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='routeoptions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
