# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('can_award_permissions', models.CharField(max_length=2048, verbose_name='can award permissions')),
                ('access_from', models.DateTimeField(blank=True, null=True, verbose_name='has access from')),
                ('access_until', models.DateTimeField(blank=True, null=True, verbose_name='has access until')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Access Operator',
                'verbose_name': 'Access Operator',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(max_length=2048, verbose_name='permissions')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False, verbose_name='is expired')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name_plural': 'Access Tokens',
                'verbose_name': 'Access Token',
            },
        ),
        migrations.CreateModel(
            name='AccessTokenInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=42, verbose_name='access secret')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('expires', models.DateTimeField(null=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='access.AccessToken', verbose_name='Access Token')),
            ],
            options={
                'verbose_name_plural': 'Access Tokens Instance',
                'verbose_name': 'Access Token Instance',
            },
        ),
        migrations.CreateModel(
            name='AccessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.CharField(help_text='Usually an URL to a profile somewhere', max_length=200, unique=True, verbose_name='access name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='access.AccessOperator', verbose_name='creator')),
            ],
            options={
                'verbose_name_plural': 'Access Users',
                'verbose_name': 'Access User',
            },
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='access.AccessUser', verbose_name='Access User'),
        ),
    ]
