# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='activated'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='secret',
            field=models.CharField(default='', max_length=42, verbose_name='activation secret'),
            preserve_default=False,
        ),
    ]
