# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20161221_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoperator',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='description'),
            preserve_default=False,
        ),
    ]
