# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20161221_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstokeninstance',
            options={'verbose_name': 'Access Token Instance', 'verbose_name_plural': 'Access Token Instances'},
        ),
    ]
