# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20161223_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
