# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 08:51
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
            ],
            options={
                'verbose_name_plural': 'Inside Areas',
                'default_related_name': 'insides',
                'verbose_name': 'Inside Area',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Usually just an integer (e.g. -1, 0, 1, 2)', unique=True, verbose_name='level name')),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='level altitude')),
            ],
            options={
                'verbose_name_plural': 'Levels',
                'default_related_name': 'levels',
                'verbose_name': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='e.g. de.c3nav.33c3.base', unique=True, verbose_name='package identifier')),
                ('home_repo', models.URLField(null=True, verbose_name='URL to the home git repository')),
                ('commit_id', models.CharField(max_length=40, null=True, verbose_name='current commit id')),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='bottom coordinate')),
                ('left', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='left coordinate')),
                ('top', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='top coordinate')),
                ('right', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='right coordinate')),
                ('directory', models.CharField(max_length=100, verbose_name='folder name')),
                ('depends', models.ManyToManyField(related_name='packages', to='mapdata.Package')),
            ],
            options={
                'verbose_name_plural': 'Map Packages',
                'default_related_name': 'packages',
                'verbose_name': 'Map Package',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'default_related_name': 'rooms',
                'verbose_name': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='bottom coordinate')),
                ('left', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='left coordinate')),
                ('top', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='top coordinate')),
                ('right', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='right coordinate')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name_plural': 'Sources',
                'default_related_name': 'sources',
                'verbose_name': 'Source',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mapdata.Package', verbose_name='map package'),
        ),
        migrations.AddField(
            model_name='inside',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insides', to='mapdata.Level', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='inside',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insides', to='mapdata.Package', verbose_name='map package'),
        ),
    ]
