# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
    ]
