# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:58
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featuretitle',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='featuretitle',
            name='feature',
        ),
        migrations.AddField(
            model_name='feature',
            name='titles',
            field=c3nav.mapdata.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeatureTitle',
        ),
    ]
