# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='home_repo',
            field=models.URLField(null=True, verbose_name='URL to the home git repository'),
        ),
    ]
