# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_squashed_refactor_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRedirect',
            fields=[
                ('locationslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='redirect', serialize=False, to='mapdata.LocationSlug')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='mapdata.LocationSlug', verbose_name='target')),
            ],
            options={
                'default_related_name': 'redirect',
            },
            bases=('mapdata.locationslug',),
        ),
    ]
