# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_auto_20160926_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='feature identifier'),
        ),
        migrations.AlterField(
            model_name='package',
            name='bottom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='bottom coordinate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='commit_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='current commit id'),
        ),
        migrations.AlterField(
            model_name='package',
            name='depends',
            field=models.ManyToManyField(blank=True, to='mapdata.Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='home_repo',
            field=models.URLField(blank=True, null=True, verbose_name='URL to the home git repository'),
        ),
        migrations.AlterField(
            model_name='package',
            name='left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='left coordinate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='right coordinate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='top',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='top coordinate'),
        ),
    ]
