# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_auto_20160926_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='feature identifier'),
        ),
    ]
