# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_package_home_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='commit_id',
            field=models.CharField(max_length=40, null=True, verbose_name='current commit id'),
        ),
    ]
