# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_door_obstacle'),
    ]

    operations = [
        migrations.RenameModel('Inside', 'Building'),
        migrations.RenameModel('Room', 'Area')
    ]
