# Generated by Django 2.1.4 on 2018-12-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_fix_broken_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='access_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='mapdata.AccessRestriction', verbose_name='Access Restriction'),
        ),
    ]
