# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


def set_space_level_category(apps, schema_editor):
    Space = apps.get_model('mapdata', 'Space')
    Space.objects.filter(level='').update(level='normal')
    Space.objects.filter(category='').update(category='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0003_space_outside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='level',
        ),
        migrations.AlterField(
            model_name='space',
            name='category',
            field=models.CharField(choices=[('normal', 'normal'), ('stairs', 'stairs'), ('escalator', 'escalator'), ('elevator', 'elevator')], default='normal', max_length=16, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='space',
            name='level',
            field=models.CharField(choices=[('normal', 'normal'), ('upper', 'upper'), ('lower', 'lower')], default='normal', max_length=16, verbose_name='level'),
        ),
        migrations.RunPython(set_space_level_category),
    ]
