# Generated by Django 2.1.4 on 2018-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0003_column_access_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapupdate',
            name='type',
            field=models.CharField(choices=[('changeset', 'changeset applied'), ('direct_edit', 'direct edit'), ('control_panel', 'via control panel'), ('management', 'manage.py clearmapcache')], max_length=32),
        ),
    ]
