# Generated by Django 2.1.4 on 2018-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0004_mapupdate_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapupdate',
            options={'default_related_name': 'mapupdates', 'get_latest_by': 'datetime', 'ordering': ('datetime',), 'verbose_name': 'Map update', 'verbose_name_plural': 'Map updates'},
        ),
        migrations.AddField(
            model_name='altitudearea',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='altitudemarker',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='area',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='building',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='column',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='door',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='hole',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='lineobstacle',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='poi',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='ramp',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='space',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='stair',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
        migrations.AddField(
            model_name='wifimeasurement',
            name='import_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='import tag'),
        ),
    ]
