# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:35
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0004_auto_20161128_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsides', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsides', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name_plural': 'Outside Areas',
                'default_related_name': 'outsides',
                'verbose_name': 'Outside Area',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Inside Area', 'verbose_name_plural': 'Inside Areas'},
        ),
    ]
