# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0004_space_level_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationslug',
            options={'verbose_name': 'Location with Slug', 'verbose_name_plural': 'Lucation with Slug'},
        ),
        migrations.AlterField(
            model_name='locationslug',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
