# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0004_auto_20160920_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mapdata.Level', verbose_name='level'),
            preserve_default=False,
        ),
    ]
