# Generated by Django 2.1.4 on 2018-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0005_geometry_import_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='icon',
            field=models.CharField(blank=True, help_text='any material icons name', max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.CharField(blank=True, help_text='any material icons name', max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='icon',
            field=models.CharField(blank=True, help_text='any material icons name', max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='poi',
            name='icon',
            field=models.CharField(blank=True, help_text='any material icons name', max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='space',
            name='icon',
            field=models.CharField(blank=True, help_text='any material icons name', max_length=32, null=True, verbose_name='icon'),
        ),
    ]
