# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 19:03
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0006_auto_20161128_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'default_related_name': 'elevators',
                'verbose_name': 'Elevator',
                'verbose_name_plural': 'Elevators',
            },
        ),
        migrations.CreateModel(
            name='ElevatorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('button', models.SlugField(max_length=10, verbose_name='Button label')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='mapdata.Elevator')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevatorlevels', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevatorlevels', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'default_related_name': 'elevatorlevels',
                'verbose_name': 'Elevator Level',
                'verbose_name_plural': 'Elevator Levels',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mapdata.Level', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='room',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mapdata.Package', verbose_name='map package'),
        ),
    ]
