# Generated by Django 2.1.4 on 2018-12-23 16:46

import c3nav.mapdata.fields
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0006_location_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroupcategory',
            name='help_text',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='', plural_name='help_texts', verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='area',
            name='slow_down_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='values of overlapping areas get multiplied!', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='slow down factor'),
        ),
    ]
