# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0007_assign_hole_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='section',
        ),
        migrations.AlterField(
            model_name='area',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='point',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='space',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='background color'),
        ),
    ]
