# Generated by Django 2.1.4 on 2018-12-25 22:01

import c3nav.mapdata.models.locations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0007_location_group_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslug',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, validators=[c3nav.mapdata.models.locations.validate_slug], verbose_name='Slug'),
        ),
    ]
