# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 10:48
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0008_hole'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('levels', models.ManyToManyField(related_name='levelconnectors', to='mapdata.Level', verbose_name='levels')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelconnectors', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'default_related_name': 'levelconnectors',
                'verbose_name_plural': 'Level Connectors',
                'verbose_name': 'Level Connector',
            },
        ),
    ]
