# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0009_levelconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='intermediate',
            field=models.BooleanField(default=False, verbose_name='intermediate level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevatorlevel',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elevatorlevels', to='mapdata.Elevator'),
        ),
    ]
