# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0010_auto_20161203_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacle',
            name='height',
        ),
        migrations.AddField(
            model_name='obstacle',
            name='crop_to_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops_obstacles', to='mapdata.Level', verbose_name='crop to other level'),
        ),
    ]
