# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0012_rename_section_to_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslug',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
    ]
