# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 09:37
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0012_auto_20161204_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
            ],
            options={
                'default_related_name': 'stairs',
                'verbose_name_plural': 'Stairs',
                'verbose_name': 'Stair',
            },
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['altitude'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AddField(
            model_name='stair',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stairs', to='mapdata.Level', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='stair',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stairs', to='mapdata.Package', verbose_name='map package'),
        ),
    ]
