# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:20
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0013_auto_20161208_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineObstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='obstacle width')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineobstacles', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineobstacles', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name_plural': 'Line Obstacles',
                'default_related_name': 'lineobstacles',
                'verbose_name': 'Line Obstacle',
            },
        ),
    ]
