# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0015_auto_20161208_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineobstacle',
            old_name='altitude',
            new_name='width',
        ),
    ]
