# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0016_auto_20161208_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineobstacle',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4, verbose_name='obstacle width'),
        ),
    ]
