# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0016_remove_source_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='POI',
        ),
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name': 'Point of Interest', 'verbose_name_plural': 'Points of Interest'},
        ),
        migrations.AlterField(
            model_name='poi',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='pois', to='mapdata.LocationGroup',
                                         verbose_name='Location Groups'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='locationslug_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                       primary_key=True, related_name='pois', serialize=False,
                                       to='mapdata.LocationSlug'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois',
                                    to='mapdata.Space', verbose_name='space'),
        ),
    ]
