# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0018_auto_20161212_1205'),
    ]

    operations = [
        migrations.RenameModel('AreaOfInterest', 'AreaLocation'),
        migrations.RenameModel('GroupOfInterest', 'LocationGroup'),
    ]
