# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0019_location_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroupcategory',
            name='allow_areas',
            field=models.BooleanField(db_index=True, default=True, verbose_name='allow areas'),
        ),
        migrations.AddField(
            model_name='locationgroupcategory',
            name='allow_levels',
            field=models.BooleanField(db_index=True, default=True, verbose_name='allow levels'),
        ),
        migrations.AddField(
            model_name='locationgroupcategory',
            name='allow_pois',
            field=models.BooleanField(db_index=True, default=True, verbose_name='allow pois'),
        ),
        migrations.AddField(
            model_name='locationgroupcategory',
            name='allow_spaces',
            field=models.BooleanField(db_index=True, default=True, verbose_name='allow spaces'),
        ),
        migrations.AddField(
            model_name='locationgroupcategory',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='locationgroupcategory',
            name='single',
            field=models.BooleanField(default=False, verbose_name='single selection'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='mapdata.LocationGroupCategory', verbose_name='Category'),
        ),
    ]
