# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0019_auto_20161216_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arealocation',
            options={'verbose_name': 'Area Location', 'verbose_name_plural': 'Area Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationgroup',
            options={'verbose_name': 'Location Group', 'verbose_name_plural': 'Location Groups'},
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='arealocations', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arealocations', to='mapdata.Level', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arealocations', to='mapdata.Package', verbose_name='map package'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationgroups', to='mapdata.Package', verbose_name='map package'),
        ),
    ]
