# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0020_auto_20170710_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationgroup',
            options={'ordering': ('-priority',), 'verbose_name': 'Location Group', 'verbose_name_plural': 'Location Groups'},
        ),
        migrations.AlterModelOptions(
            name='locationgroupcategory',
            options={'ordering': ('-priority',), 'verbose_name': 'Location Group Category', 'verbose_name_plural': 'Location Group Categories'},
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
