# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 23:54
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0021_auto_20161217_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('direction', models.BooleanField(choices=[(True, 'up'), (False, 'down')], verbose_name='direction')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalators', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalators', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name': 'Escalator',
                'default_related_name': 'escalators',
                'verbose_name_plural': 'Escalators',
            },
        ),
    ]
