# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0022_remove_space_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationgroup',
            options={'ordering': ('-category__priority', '-priority'), 'verbose_name': 'Location Group', 'verbose_name_plural': 'Location Groups'},
        ),
    ]
