# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0024_oneway'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealocation',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can be used to describe a position'),
        ),
        migrations.AddField(
            model_name='arealocation',
            name='can_search',
            field=models.BooleanField(default=True, verbose_name='can be searched'),
        ),
        migrations.AddField(
            model_name='arealocation',
            name='location_type',
            field=models.CharField(choices=[('level', 'Level name'), ('area', 'General Area'), ('room', 'Room'), ('roomsegment', 'Room Segment'), ('poi', 'Point of Interest')], default='room', max_length=20, verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='can_search',
            field=models.BooleanField(default=True, verbose_name='can be searched'),
        ),
    ]
