# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0025_auto_20161219_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealocation',
            name='location_type',
            field=models.CharField(choices=[('level', 'Level'), ('area', 'General Area'), ('room', 'Room'), ('roomsegment', 'Room Segment'), ('poi', 'Point of Interest')], max_length=20, verbose_name='Location Type'),
        ),
    ]
