# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0028_auto_20161219_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealocation',
            name='routing_inclusion',
            field=models.CharField(choices=[('default', 'Default, include if map package is unlocked'), ('allow_avoid', 'Included, but allow excluding'), ('allow_include', 'Avoided, but allow including'), ('needs_permission', 'Avoided, needs permission to include')], default='default', max_length=20, verbose_name='Routing Inclusion'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='routing_inclusion',
            field=models.CharField(choices=[('default', 'Default, include if map package is unlocked'), ('allow_avoid', 'Included, but allow excluding'), ('allow_include', 'Avoided, but allow including'), ('needs_permission', 'Avoided, needs permission to include')], default='default', max_length=20, verbose_name='Routing Inclusion'),
        ),
    ]
