# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0029_auto_20161221_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationgroup',
            name='routing_inclusion',
        ),
    ]
