# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0030_remove_locationgroup_routing_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroup',
            name='compiled_room',
            field=models.BooleanField(default=False, verbose_name='describes a compiled room'),
        ),
    ]
