# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0030_altitudes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['base_altitude'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.RenameField(
            model_name='level',
            old_name='ordering',
            new_name='base_altitude',
        ),
        migrations.AlterField(
            model_name='level',
            name='base_altitude',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True, verbose_name='base altitude'),
        ),
    ]
