# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0031_locationgroup_compiled_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealocation',
            name='routing_inclusion',
            field=models.CharField(choices=[('default', 'Default, include if map package is unlocked'), ('allow_avoid', 'Included, but allow excluding'), ('allow_include', 'Avoided, but allow including'), ('needs_permission', 'Excluded, needs permission to include')], default='default', max_length=20, verbose_name='Routing Inclusion'),
        ),
    ]
