# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 12:23
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0032_remove_graphnode_space_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altitudearea',
            name='geometry',
            field=c3nav.mapdata.fields.GeometryField(default=None, geomtype='multipolygon'),
        ),
    ]
