# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0033_auto_20161224_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealocation',
            name='color',
            field=models.CharField(blank=True, help_text='if set, has to be a valid color for svg images', max_length=16, null=True, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='color',
            field=models.CharField(blank=True, help_text='if set, has to be a valid color for svg images', max_length=16, null=True, verbose_name='background color'),
        ),
    ]
