# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0033_auto_20170807_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='default_height',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6, verbose_name='default space height'),
        ),
        migrations.AddField(
            model_name='lineobstacle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=6, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=6, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='space',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='lineobstacle',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4, verbose_name='width'),
        ),
    ]
