# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 11:54
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0034_auto_20161224_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuffedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('geometry', c3nav.mapdata.fields.GeometryField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffedareas', to='mapdata.Level', verbose_name='level')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffedareas', to='mapdata.Package', verbose_name='map package')),
            ],
            options={
                'verbose_name_plural': 'Stuffed Areas',
                'default_related_name': 'stuffedareas',
                'verbose_name': 'Stuffed Area',
            },
        ),
        migrations.AlterField(
            model_name='elevatorlevel',
            name='override_altitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='override level altitude'),
        ),
    ]
