# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0035_auto_20161226_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealocation',
            name='bssids',
            field=models.TextField(blank=True, help_text='newline separated', verbose_name='BSSIDs'),
        ),
    ]
