# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0036_geometry_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='geoms_cache',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
