# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapdata', '0038_level_render_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altitudearea',
            options={'ordering': ('altitude',), 'verbose_name': 'Altitude Area', 'verbose_name_plural': 'Altitude Areas'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'base_manager_name': 'objects', 'ordering': ['base_altitude'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
    ]
