# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 09:55
from __future__ import unicode_literals

from django.db import migrations


def fill_area_model(apps, schema_editor):
    Area = apps.get_model('mapdata', 'Area')
    for model_name in ('Room', 'Outside'):
        Model_ = apps.get_model('mapdata', model_name)
        for obj in Model_.objects.all():
            Area.objects.create(
                name=obj.name,
                geometry=obj.geometry,
                level=obj.level,
                public=obj.public,
                categories='',
                layer='',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0040_auto_20170504_0953'),
    ]

    operations = [
        migrations.RunPython(fill_area_model),
    ]
