# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0041_level_short_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='short_label',
            field=models.SlugField(max_length=20, unique=True, verbose_name='short label'),
        ),
    ]
