# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0041_room_outside_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outside',
            name='level',
        ),
        migrations.RemoveField(
            model_name='room',
            name='level',
        ),
        migrations.DeleteModel(
            name='Outside',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
