# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0042_auto_20170504_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='categories',
            new_name='category',
        ),
    ]
