# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0042_auto_20171031_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can describe'),
        ),
        migrations.AlterField(
            model_name='level',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can describe'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can describe'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can describe'),
        ),
        migrations.AlterField(
            model_name='space',
            name='can_describe',
            field=models.BooleanField(default=True, verbose_name='can describe'),
        ),
    ]
