# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0043_auto_20170504_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelconnector',
            name='levels',
        ),
        migrations.DeleteModel(
            name='LevelConnector',
        ),
    ]
