# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0044_mapupdate_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='door_height',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='door height'),
        ),
    ]
