# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0045_level_door_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='render_data',
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['base_altitude'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
    ]
