# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0046_assign_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalator',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lineobstacle',
            name='level',
        ),
        migrations.RemoveField(
            model_name='obstacle',
            name='level',
        ),
        migrations.RemoveField(
            model_name='stair',
            name='level',
        ),
        migrations.RemoveField(
            model_name='stuffedarea',
            name='level',
        ),
    ]
