# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:03
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0048_ramp'),
    ]

    operations = [
        migrations.AddField(
            model_name='altitudearea',
            name='altitude2',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='second altitude'),
        ),
        migrations.AddField(
            model_name='altitudearea',
            name='point1',
            field=c3nav.mapdata.fields.GeometryField(default=None, geomtype='point', null=True),
        ),
        migrations.AddField(
            model_name='altitudearea',
            name='point2',
            field=c3nav.mapdata.fields.GeometryField(default=None, geomtype='point', null=True),
        ),
    ]
