# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0048_elevator_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatorlevel',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='elevatorlevel',
            name='level',
        ),
        migrations.DeleteModel(
            name='Elevator',
        ),
        migrations.DeleteModel(
            name='ElevatorLevel',
        ),
    ]
