# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 11:33
from __future__ import unicode_literals

from django.db import migrations


def categorize_intermediate_areas(apps, schema_editor):
    Level = apps.get_model('mapdata', 'Level')
    for level in Level.objects.filter(intermediate=True):
        for area in level.areas.filter(category=''):
            area.category = 'escalator' if area.escalators.count() else 'stairs'
            area.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0049_auto_20170505_1125'),
    ]

    operations = [
        migrations.RunPython(categorize_intermediate_areas),
    ]
