# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0049_auto_20170505_1125'),
    ]

    operations = [
    ]
