# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 11:46
from __future__ import unicode_literals

from django.db import migrations


def move_intermediate_areas(apps, schema_editor):
    Level = apps.get_model('mapdata', 'Level')
    for level in Level.objects.filter(intermediate=True):
        lower_level = Level.objects.filter(altitude__lt=level.altitude).order_by('-altitude').first()
        upper_level = Level.objects.filter(altitude__gt=level.altitude).order_by('altitude').first()
        for area in level.areas.all():
            area.level = lower_level
            area.layer = 'upper'
            area.save()

            areaitems = []
            for c in ('escalators', 'obstacles', 'lineobstacles', 'stairs', 'stuffedareas'):
                areaitems.extend(getattr(area, c).all())

            print(areaitems)

            area.pk = None
            area.name += '_'
            area.level = upper_level
            area.layer = 'lower'
            area.save()

            for areaitem in areaitems:
                areaitem.pk = None
                areaitem.name += '-_'
                areaitem.area = area
                areaitem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0050_categorize_intermediate_areas'),
    ]

    operations = [
        migrations.RunPython(move_intermediate_areas),
    ]
