# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 13:35
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0051_auto_20171125_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='default_height',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default space height'),
        ),
        migrations.AlterField(
            model_name='level',
            name='door_height',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='door height'),
        ),
        migrations.AlterField(
            model_name='lineobstacle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='space',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='height'),
        ),
    ]
