# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 12:09
from __future__ import unicode_literals

from django.db import migrations


def delete_intermediate_levels(apps, schema_editor):
    Level = apps.get_model('mapdata', 'Level')
    Level.objects.filter(intermediate=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0051_move_intermediate_areas'),
    ]

    operations = [
        migrations.RunPython(delete_intermediate_levels),
        migrations.RemoveField(
            model_name='level',
            name='intermediate',
        ),
    ]
