# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:28
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0052_auto_20171125_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrestriction',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='area',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='level',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='locationgroupcategory',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='space',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.AlterField(
            model_name='waytype',
            name='titles',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='{model_name} {pk}',
                                                 plural_name='titles'),
        ),
        migrations.RenameField(
            model_name='accessrestriction',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='locationgroup',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='locationgroupcategory',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='poi',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='waytype',
            old_name='titles',
            new_name='title',
        ),
    ]
