# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 12:16
from __future__ import unicode_literals

from django.db import migrations


def delete_crop_to_level_obstacles(apps, schema_editor):
    Obstacle = apps.get_model('mapdata', 'Obstacle')
    Obstacle.objects.filter(crop_to_level__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0053_auto_20170505_1212'),
    ]

    operations = [
        migrations.RunPython(delete_crop_to_level_obstacles),
        migrations.RemoveField(
            model_name='obstacle',
            name='crop_to_level',
        ),
    ]
