# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:28
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0053_i18nfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroupcategory',
            name='title_plural',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, plural_name='titles_plural', verbose_name='Title (Plural)'),
        ),
        migrations.AlterField(
            model_name='accessrestriction',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='area',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='locationgroupcategory',
            name='title',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='waytype',
            name='title',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='{model} {pk}', plural_name='titles', verbose_name='Title'),
        ),
    ]
