# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapdata', '0054_title_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_access_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='can_grant',
            field=models.BooleanField(default=False, verbose_name='can grant'),
        ),
    ]
