# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0054_remove_obstacle_crop_to_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealocation',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='locationgroup',
            old_name='name',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='door',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lineobstacle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='obstacle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stair',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stuffedarea',
            name='name',
        ),
    ]
