# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0056_auto_20170506_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineobstacle',
            old_name='area',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='obstacle',
            old_name='area',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='stair',
            old_name='area',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='stuffedarea',
            old_name='area',
            new_name='space',
        ),
    ]
