# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:23
from __future__ import unicode_literals

import c3nav.mapdata.fields
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0056_accesspermissiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='waytype',
            name='description',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='description_up',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, verbose_name='description upwards'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='extra_seconds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='extra seconds per edge'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='icon_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='icon name'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='join_edges',
            field=models.BooleanField(default=True, verbose_name='join consecutive edges'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='speed (m/s)'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='speed_up',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='speed upwards (m/s)'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='title_plural',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, plural_name='titles_plural', verbose_name='Title (Plural)'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='up_separate',
            field=models.BooleanField(default=True, verbose_name='upwards separately'),
        ),
        migrations.AddField(
            model_name='waytype',
            name='walk',
            field=models.BooleanField(default=False, verbose_name='walking'),
        ),
        migrations.AlterField(
            model_name='waytype',
            name='title',
            field=c3nav.mapdata.fields.I18nField(fallback_any=True, plural_name='titles', verbose_name='Title'),
        ),
    ]
