# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 11:42
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapdata', '0057_waytype_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', c3nav.mapdata.fields.GeometryField(default=None, geomtype='point')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('data', c3nav.mapdata.fields.JSONField(verbose_name='Measurement list')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wifi_measurements', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_measurements', to='mapdata.Space', verbose_name='space')),
            ],
            options={
                'verbose_name': 'Wi-Fi Measurement',
                'verbose_name_plural': 'Wi-Fi Measurements',
                'default_related_name': 'wifi_measurements',
            },
        ),
    ]
