# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0057_auto_20170506_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
