# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0058_auto_20170506_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='Section',
        ),
    ]
