# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0059_auto_20170507_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealocation',
            old_name='level',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='level',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='level',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='hole',
            old_name='level',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='level',
            new_name='section',
        ),
    ]
