# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 14:30
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0060_access_permission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDecription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', c3nav.mapdata.fields.I18nField(verbose_name='description')),
                ('origin_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_cross_descriptions', to='mapdata.Space', verbose_name='origin space')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_descriptions', to='mapdata.Space', verbose_name='space')),
                ('target_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_enter_descriptions', to='mapdata.Space', verbose_name='target space')),
            ],
            options={
                'verbose_name': 'Cross description',
                'verbose_name_plural': 'Cross descriptions',
                'default_related_name': 'cross_descriptions',
            },
        ),
        migrations.CreateModel(
            name='LeaveDecription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', c3nav.mapdata.fields.I18nField(verbose_name='description')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_descriptions', to='mapdata.Space', verbose_name='space')),
                ('target_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_descriptions', to='mapdata.Space', verbose_name='target space')),
            ],
            options={
                'verbose_name': 'Leave description',
                'verbose_name_plural': 'Leave descriptions',
                'default_related_name': 'leave_descriptions',
            },
        ),
    ]
