# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0060_auto_20170507_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealocation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arealocations', to='mapdata.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='building',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='mapdata.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='door',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='mapdata.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='mapdata.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='altitude',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True, verbose_name='section altitude'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.SlugField(unique=True, verbose_name='section name'),
        ),
        migrations.AlterField(
            model_name='space',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='mapdata.Section', verbose_name='section'),
        ),
    ]
