# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0061_space_based_route_descriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrossDecription',
            new_name='CrossDescription',
        ),
        migrations.RenameModel(
            old_name='LeaveDecription',
            new_name='LeaveDescription',
        ),
    ]
