# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0062_typos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crossdescription',
            unique_together=set([('space', 'origin_space', 'target_space')]),
        ),
        migrations.AlterUniqueTogether(
            name='leavedescription',
            unique_together=set([('space', 'target_space')]),
        ),
    ]
