# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapdata', '0063_descriptions_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspermissiontoken',
            options={'verbose_name': 'Access Permission Token', 'verbose_name_plural': 'Access Permission Tokens'},
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='unique_key',
            field=models.CharField(max_length=32, null=True, verbose_name='unique key'),
        ),
        migrations.AddField(
            model_name='accesspermissiontoken',
            name='unique_key',
            field=models.CharField(max_length=32, null=True, verbose_name='unique key'),
        ),
        migrations.AlterUniqueTogether(
            name='accesspermission',
            unique_together=set([('author', 'unique_key')]),
        ),
    ]
