# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0064_auto_20170509_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='layer',
            new_name='level',
        ),
    ]
