# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0065_auto_20170509_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='door',
            name='level',
            field=models.CharField(choices=[('', 'normal'), ('upper', 'upper'), ('lower', 'lower')], default='', max_length=16, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='space',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='mapdata.Section', verbose_name='section'),
        ),
    ]
