# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 14:08
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0065_access_restriction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slow_down_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='slow down factor'),
        ),
    ]
