# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 15:13
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0066_area_slow_down_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='enter_description',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_language=None, verbose_name='Enter description'),
        ),
    ]
