# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0066_auto_20170509_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuffedArea',
            new_name='Area',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
