# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 01:19
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0067_space_enter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='waytype',
            name='level_change_description',
            field=c3nav.mapdata.fields.I18nField(verbose_name='level change description'),
        ),
    ]
