# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0068_area_stuffed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='mapdata.Space', verbose_name='space'),
        ),
    ]
