# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0068_waytype_level_change_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapupdate',
            name='geometries_changed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
