# Generated by Django 2.2.8 on 2019-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0072_make_wifi_measurement_author_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroup',
            name='hierarchy',
            field=models.IntegerField(db_index=True, default=0, verbose_name='hierarchy'),
        ),
    ]
