# Generated by Django 2.2.8 on 2019-12-21 15:45

import c3nav.mapdata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0072_make_wifi_measurement_author_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLocationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('title', c3nav.mapdata.fields.I18nField(fallback_any=True, plural_name='titles', verbose_name='Title')),
                ('help_text', c3nav.mapdata.fields.I18nField(fallback_any=True, fallback_value='', plural_name='help_texts', verbose_name='Help text')),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('data_type', models.CharField(choices=[('str', 'string'), ('int', 'integer')], max_length=20, verbose_name='Data Type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('default', models.TextField(blank=True, null=True, verbose_name='default value')),
                ('groups', models.ManyToManyField(related_name='customlocationfields', to='mapdata.LocationGroup', verbose_name='Location Groups')),
            ],
            options={
                'verbose_name': 'Custom Location Field',
                'verbose_name_plural': 'Custom Location Fields',
                'ordering': ('-priority',),
                'default_related_name': 'customlocationfields',
            },
        ),
    ]
