# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0072_auto_20170510_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationgroup',
            name='slug',
        ),
    ]
