# Generated by Django 2.2.8 on 2019-12-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0073_locationgroup_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='show_label',
            field=models.CharField(choices=[('inherit', 'inherit from groups (default)'), ('show_text', 'yes, show the title'), ('no', "don't show")], default='inherit', max_length=16, verbose_name='show label'),
        ),
        migrations.AddField(
            model_name='level',
            name='show_label',
            field=models.CharField(choices=[('inherit', 'inherit from groups (default)'), ('show_text', 'yes, show the title'), ('no', "don't show")], default='inherit', max_length=16, verbose_name='show label'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='show_labels',
            field=models.CharField(choices=[('no', 'no (default)'), ('show_text', 'yes, show the title')], default='no', help_text='unless location specifies otherwise', max_length=16, verbose_name='show labels'),
        ),
        migrations.AddField(
            model_name='poi',
            name='show_label',
            field=models.CharField(choices=[('inherit', 'inherit from groups (default)'), ('show_text', 'yes, show the title'), ('no', "don't show")], default='inherit', max_length=16, verbose_name='show label'),
        ),
        migrations.AddField(
            model_name='space',
            name='show_label',
            field=models.CharField(choices=[('inherit', 'inherit from groups (default)'), ('show_text', 'yes, show the title'), ('no', "don't show")], default='inherit', max_length=16, verbose_name='show label'),
        ),
    ]
