# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0073_remove_locationgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='mapdata.LocationSlug', verbose_name='location slug'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='slug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationgroups', to='mapdata.LocationSlug', verbose_name='location slug'),
        ),
        migrations.AlterField(
            model_name='point',
            name='slug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='mapdata.LocationSlug', verbose_name='location slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mapdata.LocationSlug', verbose_name='location slug'),
        ),
        migrations.AlterField(
            model_name='space',
            name='slug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='mapdata.LocationSlug', verbose_name='location slug'),
        ),
    ]
