# Generated by Django 2.2.8 on 2019-12-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0075_label_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelsettings',
            options={'default_related_name': 'labelsettings', 'ordering': ('min_zoom', '-font_size'), 'verbose_name': 'Label Settings', 'verbose_name_plural': 'Label Settings'},
        ),
        migrations.AddField(
            model_name='lineobstacle',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='color (optional)'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='color (optional)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='label_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='mapdata.LabelSettings', verbose_name='label settings'),
        ),
        migrations.AlterField(
            model_name='level',
            name='label_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='mapdata.LabelSettings', verbose_name='label settings'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='label_settings',
            field=models.ForeignKey(blank=True, help_text='unless location specifies otherwise', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locationgroups', to='mapdata.LabelSettings', verbose_name='label settings'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='label_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pois', to='mapdata.LabelSettings', verbose_name='label settings'),
        ),
        migrations.AlterField(
            model_name='space',
            name='label_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='mapdata.LabelSettings', verbose_name='label settings'),
        ),
    ]
