# Generated by Django 2.2.8 on 2019-12-22 19:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0076_obstacle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineobstacle',
            name='altitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='altitude above ground'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='altitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='altitude above ground'),
        ),
    ]
