# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0076_auto_20170510_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
