# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:41
from __future__ import unicode_literals

import c3nav.mapdata.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0078_auto_20170510_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('locationslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='locationgroups', serialize=False, to='mapdata.LocationSlug')),
                ('titles', c3nav.mapdata.fields.JSONField(default={})),
                ('can_search', models.BooleanField(default=True, verbose_name='can be searched')),
                ('can_describe', models.BooleanField(default=True, verbose_name='can be used to describe a position')),
                ('color', models.CharField(blank=True, help_text='if set, has to be a valid color for svg images', max_length=16, null=True, verbose_name='background color')),
                ('public', models.BooleanField(default=True, verbose_name='public')),
                ('compiled_room', models.BooleanField(default=False, verbose_name='is a compiled room')),
            ],
            options={
                'verbose_name': 'Location Group',
                'verbose_name_plural': 'Location Groups',
                'default_related_name': 'locationgroups',
            },
            bases=('mapdata.locationslug', models.Model),
        ),
        migrations.AlterField(
            model_name='legacylocationgroup',
            name='locationslug_ptr',
            field=models.OneToOneField(db_column='locationslug_ptr', on_delete=django.db.models.deletion.CASCADE, related_name='legacylocationgroups', to='mapdata.LocationSlug'),
        ),
    ]
