# Generated by Django 2.2.8 on 2019-12-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0079_auto_20191224_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_groups',
            field=models.ManyToManyField(blank=True, help_text='select all groups that apply, if any', limit_choices_to={'can_report_missing': True}, related_name='_report_created_groups_+', to='mapdata.LocationGroup', verbose_name='location groups'),
        ),
    ]
