# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0079_auto_20170510_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealocation',
            old_name='groups',
            new_name='legacygroups',
        ),
    ]
