# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0080_auto_20170510_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealocation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='arealocations', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
    ]
