# Generated by Django 2.2.8 on 2019-12-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0080_auto_20191224_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportupdate',
            options={'default_related_name': 'reportupdates', 'ordering': ('datetime',), 'verbose_name': 'Report update', 'verbose_name_plural': 'Report updates'},
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportupdates', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='public',
            field=models.BooleanField(verbose_name='comment is public'),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='mapdata.Report'),
        ),
    ]
