# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0081_arealocation_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='areas', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
        migrations.AlterField(
            model_name='point',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='points', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
        migrations.AlterField(
            model_name='section',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sections', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
        migrations.AlterField(
            model_name='space',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='mapdata.LocationGroup', verbose_name='Location Groups'),
        ),
    ]
