# Generated by Django 2.2.8 on 2019-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0082_dynamiclocation_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='position',
            name='location_id',
        ),
        migrations.AddField(
            model_name='position',
            name='coordinates_id',
            field=models.CharField(max_length=48, null=True, verbose_name='coordinates'),
        ),
        migrations.AddField(
            model_name='position',
            name='last_coordinates_update',
            field=models.DateTimeField(null=True, verbose_name='last coordinates update'),
        ),
    ]
