# Generated by Django 2.2.8 on 2019-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0083_auto_20191227_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for no timeout', verbose_name='timeout (in seconds)'),
        ),
    ]
