# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0083_auto_20170510_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacylocationgroup',
            name='locationslug_ptr',
        ),
        migrations.RemoveField(
            model_name='arealocation',
            name='legacygroups',
        ),
        migrations.DeleteModel(
            name='LegacyLocationGroup',
        ),
    ]
