# Generated by Django 2.2.8 on 2019-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0084_position_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroupcategory',
            name='allow_dynamic_locations',
            field=models.BooleanField(db_index=True, default=True, verbose_name='allow dynamic locations'),
        ),
    ]
