# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0085_assign_location_level_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='stuffed',
            field=models.BooleanField(default=False, verbose_name='stuffed area'),
        ),
    ]
