# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0087_assign_location_roomsegment_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationgroup',
            name='compiled_area',
            field=models.BooleanField(default=False, verbose_name='is a compiled area'),
        ),
    ]
