# Generated by Django 4.2.1 on 2023-11-24 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapdata", "0087_rangingbeacon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="api_secret",
        ),
    ]
