# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0089_assign_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealocation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='arealocation',
            name='section',
        ),
        migrations.DeleteModel(
            name='AreaLocation',
        ),
    ]
