# Generated by Django 4.2.7 on 2023-12-19 14:41

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapdata", "0090_alter_report_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="main_point",
            field=c3nav.mapdata.fields.GeometryField(
                default=None,
                geomtype="point",
                help_text="main routing point (optional)",
                null=True,
            ),
        ),
    ]
