# Generated by Django 4.2.7 on 2023-12-20 22:25

import c3nav.mapdata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0092_accesspermission_by_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrestriction',
            old_name='open',
            new_name='public',
        ),
        migrations.AlterField(
            model_name='accessrestriction',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
