# Generated by Django 4.2.7 on 2023-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0094_hub_import_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='import_block_data',
            field=models.BooleanField(default=False, verbose_name="don't change metadata on import"),
        ),
        migrations.AddField(
            model_name='area',
            name='import_block_geom',
            field=models.BooleanField(default=False, verbose_name="don't change geometry on import"),
        ),
        migrations.AddField(
            model_name='dynamiclocation',
            name='import_block_data',
            field=models.BooleanField(default=False, verbose_name="don't change metadata on import"),
        ),
        migrations.AddField(
            model_name='dynamiclocation',
            name='import_block_geom',
            field=models.BooleanField(default=False, verbose_name="don't change geometry on import"),
        ),
        migrations.AddField(
            model_name='level',
            name='import_block_data',
            field=models.BooleanField(default=False, verbose_name="don't change metadata on import"),
        ),
        migrations.AddField(
            model_name='level',
            name='import_block_geom',
            field=models.BooleanField(default=False, verbose_name="don't change geometry on import"),
        ),
        migrations.AddField(
            model_name='poi',
            name='import_block_data',
            field=models.BooleanField(default=False, verbose_name="don't change metadata on import"),
        ),
        migrations.AddField(
            model_name='poi',
            name='import_block_geom',
            field=models.BooleanField(default=False, verbose_name="don't change geometry on import"),
        ),
        migrations.AddField(
            model_name='space',
            name='import_block_data',
            field=models.BooleanField(default=False, verbose_name="don't change metadata on import"),
        ),
        migrations.AddField(
            model_name='space',
            name='import_block_geom',
            field=models.BooleanField(default=False, verbose_name="don't change geometry on import"),
        ),
    ]
