# Generated by Django 4.2.7 on 2023-12-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0095_accesspermission_for_session'),
        ('mapdata', '0095_import_block'),
    ]

    operations = [
    ]
