# Generated by Django 4.2.7 on 2023-12-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0096_merge_20231225_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altitudearea',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='altitudemarker',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='area',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='building',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='column',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='door',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='lineobstacle',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='ramp',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='rangingbeacon',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='space',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
    ]
