# Generated by Django 4.2.7 on 2024-01-05 10:27

from django.db import migrations

sql_up = '''
-- create an obstacle group for every distinct obstacle color
insert into mapdata_obstaclegroup (color, titles)
select color as color,
       json_build_object('en', concat('Color ', color)) as titles
from
                          (select distinct color
                            from mapdata_obstacle
                            where color is not null
                            union 
                            select distinct color
                            from mapdata_lineobstacle
                            where color is not null) as obstacle_colors;

-- set the groups for colored obstacles to the previously created group with that color
update mapdata_obstacle as o
set group_id = g.id
from mapdata_obstaclegroup g
where g.color = o.color;

update mapdata_lineobstacle as o
set group_id = g.id
from mapdata_obstaclegroup g
where g.color = o.color;
'''

sql_down = '''
-- set obstacle color from associated group color and remove group
update mapdata_obstacle as o
set color = g.color, group_id = null
from mapdata_obstaclegroup g
where g.id = o.group_id;

update mapdata_lineobstacle as o
set color = g.color, group_id = null
from mapdata_obstaclegroup g
where g.id = o.group_id;

-- delete groups
delete from mapdata_obstaclegroup where true;
'''


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0099_theming'),
    ]

    operations = [
        migrations.RunSQL(sql_up, sql_down)
    ]
