# Generated by Django 4.2.7 on 2024-01-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0100_obstaclegroup_color_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacle',
            name='color',
        )
    ]
