# Generated by Django 5.0.1 on 2024-03-10 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0101_remove_obstacle_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rangingbeacon',
            old_name='bssid',
            new_name='wifi_bssid',
        ),
        migrations.AlterField(
            model_name='rangingbeacon',
            name='wifi_bssid',
            field=models.CharField(blank=True, help_text="uses node's value if not set", max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bssid', message='Must be a lower-case bssid', regex='^([a-f0-9]{2}:){5}[a-f0-9]{2}$')], verbose_name='WiFi BSSID'),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='bluetooth_address',
            field=models.CharField(blank=True, help_text="uses node's value if not set", max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bluetooth_address', message='Must be a lower-case mac address', regex='^([a-f0-9]{2}:){5}[a-f0-9]{2}$')], verbose_name='Bluetooth Address'),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='ibeacon_major',
            field=models.PositiveIntegerField(blank=True, help_text="uses node's value if not set", null=True, verbose_name='iBeacon major value'),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='ibeacon_minor',
            field=models.PositiveIntegerField(blank=True, help_text="uses node's value if not set", null=True, verbose_name='iBeacon minor value'),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='ibeacon_uuid',
            field=models.UUIDField(blank=True, help_text="uses node's value if not set", null=True, verbose_name='iBeacon UUID'),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='node_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Node Number'),
        ),

        migrations.AddField(
            model_name='rangingbeacon',
            name='uwb_address',
            field=models.CharField(blank=True, help_text="uses node's value if not set", max_length=23, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_uwb_address', message='Must be a lower-case 8-byte UWB address', regex='^([a-f0-9]{2}:){7}[a-f0-9]{2}$')], verbose_name='UWB Address'),
        ),
        migrations.AlterField(
            model_name='wifimeasurement',
            name='data',
            field=models.JSONField(default=list, verbose_name='Measurement list'),
        ),
    ]
