# Generated by Django 5.0.3 on 2024-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0103_report_flow_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color_css_grid',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS grid color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_header_background',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS header background color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_header_text',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS header text color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_header_text_hover',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS header text hover color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_initial',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS initial/background color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_modal_backdrop',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS modal backdrop color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_overlay_background',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS overlay/label background color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_primary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS primary/accent color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_quaternary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS quaternary color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_quinary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS quinary color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_route_dots_shadow',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS route dots shadow color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_secondary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS secondary/foreground color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_shadow',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS shadow color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_css_tertiary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CSS tertiary color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_logo',
            field=models.TextField(blank=True, default='', verbose_name='Logo color (can be a CSS gradient if you really want it to)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='dark',
            field=models.BooleanField(default=False, verbose_name='This is a dark theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False, verbose_name='This is a default theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='extra_css',
            field=models.TextField(blank=True, default='', verbose_name='Extra CSS'),
        ),
        migrations.AddField(
            model_name='theme',
            name='funky',
            field=models.BooleanField(default=False, verbose_name='Funky (do not persist through a reload when uses chooses this theme)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='high_contrast',
            field=models.BooleanField(default=False, verbose_name='This is a high-contrast theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='randomize_primary_color',
            field=models.BooleanField(default=False, verbose_name='Use random primary color'),
        ),
    ]
