# Generated by Django 5.0.8 on 2024-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0109_accesspermissionssogrant_accesspermission_sso_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Root path for icon images'),
        ),
        migrations.AddField(
            model_name='theme',
            name='leaflet_marker_config',
            field=models.TextField(blank=True, default='', verbose_name='Leaflet marker config override'),
        ),
    ]
