# Generated by Django 5.0.8 on 2024-12-04 22:42

import c3nav.mapdata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapdata", "0111_dataoverlay_dataoverlayfeature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataoverlay",
            options={
                "default_related_name": "dataoverlays",
                "verbose_name": "Data Overlay",
                "verbose_name_plural": "Data Overlays",
            },
        ),
        migrations.AlterModelOptions(
            name="dataoverlayfeature",
            options={"default_related_name": "dataoverlayfeatures"},
        ),
        migrations.AlterModelOptions(
            name="dynamiclocation",
            options={
                "default_related_name": "dynamiclocations",
                "verbose_name": "Dynamic location",
                "verbose_name_plural": "Dynamic locations",
            },
        ),
        migrations.AlterModelOptions(
            name="locationredirect",
            options={"default_related_name": "locationredirects"},
        ),
        migrations.AlterField(
            model_name="crossdescription",
            name="description",
            field=c3nav.mapdata.fields.I18nField(
                plural_name="descriptions", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="leavedescription",
            name="description",
            field=c3nav.mapdata.fields.I18nField(
                plural_name="descriptions", verbose_name="description"
            ),
        ),
    ]
