# Generated by Django 5.0.8 on 2024-12-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0114_accessrestrictiongroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoverlay',
            name='access_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapdata.accessrestriction', verbose_name='Access Restriction'),
        ),
    ]
