# Generated by Django 5.1.3 on 2024-12-16 10:23

from django.db import migrations, models

def change_empty_to_null(apps, schema_editor):
    DataOverlay = apps.get_model('mapdata', 'DataOverlay')
    DataOverlay.objects.filter(fill_color='').update(fill_color=None)
    DataOverlay.objects.filter(stroke_color='').update(stroke_color=None)

class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0116_waytype_avoid_by_default_alter_waytype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataoverlay',
            name='fill_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default fill color'),
        ),
        migrations.AlterField(
            model_name='dataoverlay',
            name='stroke_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default stroke color'),
        ),
        migrations.RunPython(change_empty_to_null, migrations.RunPython.noop),
    ]
