# Generated by Django 5.1.3 on 2024-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0117_alter_dataoverlay_fill_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoverlay',
            name='default_geomtype',
            field=models.CharField(blank=True, choices=[('polygon', 'Polygon'), ('line', 'Line'), ('point', 'Point')], max_length=255, null=True, verbose_name='default geometry type'),
        ),
    ]
