# Generated by Django 5.1.3 on 2024-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0118_dataoverlay_default_geomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoverlay',
            name='fill_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='fill opacity'),
        ),
        migrations.AddField(
            model_name='dataoverlay',
            name='stroke_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='stroke opacity'),
        ),
        migrations.AddField(
            model_name='dataoverlayfeature',
            name='fill_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='fill opacity'),
        ),
        migrations.AddField(
            model_name='dataoverlayfeature',
            name='stroke_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='stroke opacity'),
        ),
        migrations.AlterField(
            model_name='dataoverlay',
            name='default_geomtype',
            field=models.CharField(blank=True, choices=[('polygon', 'Polygon'), ('linestring', 'Line string'), ('point', 'Point')], max_length=255, null=True, verbose_name='default geometry type'),
        ),
    ]
