# Generated by Django 5.0.8 on 2024-12-24 16:55

import c3nav.routing.schemas
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0124_beaconmeasurement_data_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangingbeacon',
            name='altitude_quest',
            field=models.BooleanField(default=True, verbose_name='altitude quest'),
        ),
    ]
