# Generated by Django 5.0.8 on 2024-12-25 15:44

import c3nav.routing.schemas
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0125_rangingbeacon_altitude_quest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Load group',
                'verbose_name_plural': 'Load groups',
                'default_related_name': 'labelgroup',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='load_group_contribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapdata.loadgroup', verbose_name='contribute to load group'),
        ),
        migrations.AddField(
            model_name='area',
            name='load_group_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapdata.loadgroup', verbose_name='display load group'),
        ),
        migrations.AddField(
            model_name='dynamiclocation',
            name='load_group_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapdata.loadgroup', verbose_name='display load group'),
        ),
        migrations.AddField(
            model_name='level',
            name='load_group_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapdata.loadgroup', verbose_name='display load group'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='load_group_contribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapdata.loadgroup', verbose_name='contribute to load group'),
        ),
        migrations.AddField(
            model_name='poi',
            name='load_group_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapdata.loadgroup', verbose_name='display load group'),
        ),
        migrations.AddField(
            model_name='space',
            name='load_group_contribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapdata.loadgroup', verbose_name='contribute to load group'),
        ),
        migrations.AddField(
            model_name='space',
            name='load_group_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapdata.loadgroup', verbose_name='display load group'),
        ),
    ]
