# Generated by Django 5.0.8 on 2024-12-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0127_alter_beaconmeasurement_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='identifyable',
            field=models.BooleanField(default=None, help_text='if unknown, this will be a quest. if yes, quests for enter, leave or cross descriptions to this room will be generated.', null=True, verbose_name='easily identifyable/findable'),
        ),
    ]
