# Generated by Django 5.1.3 on 2024-12-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0129_dataoverlay_cluster_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoverlay',
            name='edit_access_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edit_access_restrictions', to='mapdata.accessrestriction', verbose_name='Editor Access Restriction'),
        ),
    ]
