# Generated by Django 5.0.8 on 2024-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0132_dataoverlay_update_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconmeasurement',
            name='fill_quest',
            field=models.BooleanField(default=False, verbose_name='create a quest to fill this'),
        ),
    ]
