# Generated by Django 5.2 on 2025-09-06 13:31

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0138_rangingbeacon_max_observed_num_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='media_panel_done',
            field=models.BooleanField(default=False, verbose_name='All media panels mapped'),
        ),
    ]
