# Generated by Django 5.2 on 2025-12-16 14:52

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0139_space_media_panel_done_alter_rangingbeacon_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapupdate',
            name='purge_all_cache',
            field=models.BooleanField(default=False, help_text='This erases all map history when processed, meaning that all tiles and renderings need to be re-rendered. Only use after manually tampering with the database or to fix caching issues.', verbose_name='purge the entire cache'),
        ),
    ]
