# Generated by Django 5.1.5 on 2025-01-24 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def delete_null_slugs(apps, model_name):
    LocationSlug = apps.get_model('mapdata', 'LocationSlug')
    LocationSlug.objects.filter(slug__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0140_restructure_location_modeling_delete_old'),
    ]

    operations = [
        # alright, we can delete all slug models now that have slug=None and make that field not nullable
        migrations.RunPython(delete_null_slugs, migrations.RunPython.noop),
    ]
