# Generated by Django 6.0 on 2025-12-21 14:28

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0140_mapupdate_purge_all_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='internal_room_number',
            field=models.CharField(blank=True, null=True, verbose_name='Internal Room Number'),
        ),
    ]
