# Generated by Django 6.0 on 2025-12-24 11:42

import c3nav.routing.schemas
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0141_space_internal_room_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBeaconMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('data', django_pydantic_field.fields.PydanticSchemaField(config=None, default={'ibeacon': [], 'wifi': []}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=c3nav.routing.schemas.BeaconMeasurementDataSchema, verbose_name='Measurement list')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('placed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_measurement', to='mapdata.beaconmeasurement'))
            ],
            options={
                'verbose_name': 'Auto Beacon Measurement',
                'verbose_name_plural': 'Auto Beacon Measurements',
                'default_related_name': 'auto_beacon_measurements',
            },
        ),
    ]
