# Generated by Django 6.0 on 2025-12-24 14:39

import c3nav.mapdata.models.report
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0142_autobeaconmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to=c3nav.mapdata.models.report.report_image_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='can_report_missing',
            field=models.CharField(choices=[('dont_offer', "don't offer"), ('reject', 'offer in first step, then reject'), ('single', 'offer in first step, exclusive choice'), ('image', 'offer in first step, then only query image'), ('multiple', 'offer if nothing in the first step matches, multiple choice')], default='dont_offer', max_length=16, verbose_name='report missing location'),
        ),
    ]
