# Generated by Django 5.1.5 on 2025-01-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0142_restructure_location_modeling_slug_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslug',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_set', to='mapdata.locationgroup'),
        ),
        migrations.AlterField(
            model_name='locationslug',
            name='specific',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_set', to='mapdata.specificlocation'),
        ),
    ]
