# Generated by Django 5.1.5 on 2025-01-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0142_restructure_location_modeling_slug_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mapdata.specificlocation', verbose_name='location'),
        ),
    ]
