# Generated by Django 6.0 on 2026-08-13 11:15

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic_extra_types.mac_address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0143_report_image_alter_locationgroup_can_report_missing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rangingbeacon',
            name='addresses',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="uses node's value if not set", schema=django_pydantic_field.compat.django.GenericContainer(list, (pydantic_extra_types.mac_address.MacAddress,)), verbose_name='Mac Address / BSSIDs'),
        ),
    ]
