# Generated by Django 5.1.5 on 2025-01-24 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0146_restructure_location_modeling_remove_null_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslug',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(--?[a-z0-9]+)*\\Z', 'Enter a valid location slug consisting of lowercase letters, numbers or hyphens, not starting or ending with hyphens or containing consecutive hyphens.', 'invalid')], verbose_name='Slug'),
        ),
    ]
