# Generated by Django 5.1.5 on 2025-01-24 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0146_remove_location_multi_table_inheritance_remove_null_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslug',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]*[a-z]+[a-z0-9-]*\\Z', 'Enter a valid location slug consisting of lowercase letters, numbers or hyphens, with at least one letter.', 'invalid')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mapdata.specificlocation', verbose_name='location'),
        ),
        migrations.AddConstraint(
            model_name='locationslug',
            constraint=models.UniqueConstraint(condition=models.Q(('redirect', False)), fields=('group', 'specific'), name='unique_non_redirect_slugs'),
        ),

        migrations.AlterField(
            model_name='specificlocation',
            name='area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='mapdata.area'),
        ),
        migrations.AlterField(
            model_name='specificlocation',
            name='dynamiclocation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='mapdata.dynamiclocation'),
        ),
        migrations.AlterField(
            model_name='specificlocation',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='mapdata.level'),
        ),
        migrations.AlterField(
            model_name='specificlocation',
            name='poi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='mapdata.poi'),
        ),
        migrations.AlterField(
            model_name='specificlocation',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='mapdata.space'),
        ),
        migrations.AddConstraint(
            model_name='specificlocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', True), ('dynamiclocation__isnull', True), ('level__isnull', False), ('poi__isnull', True), ('space__isnull', True)), models.Q(('area__isnull', True), ('dynamiclocation__isnull', True), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', False)), models.Q(('area__isnull', False), ('dynamiclocation__isnull', True), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', True)), models.Q(('area__isnull', True), ('dynamiclocation__isnull', True), ('level__isnull', True), ('poi__isnull', False), ('space__isnull', True)), models.Q(('area__isnull', True), ('dynamiclocation__isnull', False), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', True)), models.Q(('area__isnull', True), ('dynamiclocation__isnull', True), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', True)), _connector='OR'), name='only_one_specific_location_target'),
        ),
    ]
