# Generated by Django 5.1.5 on 2025-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0146_m2m_location_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationgroup',
            options={'default_related_name': 'locationgroups', 'ordering': ('effective_order',), 'verbose_name': 'Location Group', 'verbose_name_plural': 'Location Groups'},
        ),
        migrations.AlterModelOptions(
            name='specificlocation',
            options={'default_related_name': 'specific_locations', 'ordering': ('effective_order',), 'verbose_name': 'Specific Location', 'verbose_name_plural': 'Specific Locations'},
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='effective_order',  # todo: get rid of all the stupid effective_order stuff
            field=models.PositiveIntegerField(default=2147483647),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='effective_order',
            field=models.PositiveIntegerField(default=2147483647, editable=False),
        ),
    ]
