# Generated by Django 5.1.5 on 2025-01-30 13:36

import types
import typing

import django.core.serializers.json
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models
from django.db import migrations, models
from shapely import contains, convex_hull

import c3nav.api.schema
import c3nav.mapdata.models.geometry.base
import c3nav.mapdata.permissions
import c3nav.mapdata.permissions
from c3nav.mapdata.utils.geometry.wrapped import unwrap_geom


def make_location_target_m2m(apps, model_name):
    print("\n    ...", end='')
    SpecificLocation = apps.get_model('mapdata', 'SpecificLocation')
    area_to_spaces = []
    for location in SpecificLocation.objects.select_related('area', 'area__space', 'area__space__location'):
        if location.level_id:
            location.levels.add(location.level_id)
        elif location.space_id:
            location.spaces.add(location.space_id)
        elif location.area_id:
            # if this location points to an area, and the area fully includes the space it is in,
            # point at the space and delete the area
            if contains(unwrap_geom(location.area.geometry).buffer(1), unwrap_geom(location.area.space.geometry)):
                print(f'Changing area location "{location.title}" '
                      f'to point at space "{location.area.space.location.title}" instead.\n    ...', end='')
                area_to_spaces.append([location, location.area.space])
                area = location.area
                location.area = None
                location.save()
                area.delete()
            else:
                location.areas.add(location.area_id)
        elif location.poi_id:
            location.pois.add(location.poi_id)
        elif location.dynamiclocation_id:
            location.dynamiclocations.add(location.dynamiclocation_id)
    for location, space in area_to_spaces:
        location.spaces.add(space)


def make_location_target_o2o(apps, model_name):
    print("\n    ...", end='')
    SpecificLocation = apps.get_model('mapdata', 'SpecificLocation')
    Area = apps.get_model('mapdata', 'Area')
    locations = SpecificLocation.objects.prefetch_related("levels", "spaces", "areas", "pois", "dynamiclocations")
    for target_type in ("level", "space", "area", "poi", "dynamiclocation"):
        occupied = set()
        for location in locations:
            targets = tuple(getattr(location, f"{target_type}s").all())
            for i, target in enumerate(targets):
                if target.pk in occupied:
                    if target_type == "level":
                        raise ValueError(f'Location "{location.title}" reuses level.')
                    elif target_type == "space":
                        print(f'Location "{location.title}" reuses space, '
                              f'creating area to resolve conflict.\n    ...', end='')
                        set_target = Area.objects.create(
                            space=target,
                            geometry=convex_hull(unwrap_geom(target.geometry)).buffer(0.5, join_style="round",
                                                                                      quad_segs=1)
                        )
                    else:
                        print(f'Location "{location.title}" reuses {target_type}, '
                              f'cloning it to resolve conflict.\n    ...', end='')
                        set_target = target
                        set_target.pk = None
                        set_target.save()
                else:
                    set_target = target
                if i > 0:
                    print(f'Duplicating location "{location.title}" '
                          f'so it can point at {target_type} #{set_target.pk}.\n    ...', end='')
                    location.pk = None
                    location.save()
                setattr(location, set_target._meta.model_name.lower(), set_target)
                location.save()
                occupied.add(target.pk)


def make_dynamic_location_target_m2m(apps, model_name):
    DynamicLocationTagTarget = apps.get_model('mapdata', 'DynamicLocationTagTarget')
    DynamicLocationTagTarget.objects.filter(position_secret="").delete()
    for dynamic_location_target in DynamicLocationTagTarget.objects.prefetch_related("tags"):
        dynamic_location_target.tag = dynamic_location_target.tags.get()
        dynamic_location_target.save()


def un_make_dynamic_location_m2m(apps, model_name):
    DynamicLocationTagTarget = apps.get_model('mapdata', 'DynamicLocationTagTarget')
    for dynamic_location_target in DynamicLocationTagTarget.objects.select_related("location"):
        dynamic_location_target.location.dynamiclocations.add(dynamic_location_target)


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0147_remove_location_multi_table_inheritance_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificlocation',
            name='areas',
            field=models.ManyToManyField(related_name='tags', to='mapdata.area'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='dynamiclocations',
            field=models.ManyToManyField(related_name='tags', to='mapdata.dynamiclocation'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='levels',
            field=models.ManyToManyField(related_name='tags', to='mapdata.level'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='pois',
            field=models.ManyToManyField(related_name='tags', to='mapdata.poi'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='spaces',
            field=models.ManyToManyField(related_name='tags', to='mapdata.space'),
        ),
        migrations.RunPython(make_location_target_m2m, make_location_target_o2o),
        migrations.RemoveConstraint(
            model_name='specificlocation',
            name='only_one_specific_location_target',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='area',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='dynamiclocation',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='space',
        ),

        migrations.AddField(
            model_name='level',
            name='effective_bottom',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='bottom coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_left',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='left coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_right',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=6, verbose_name='right coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_top',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=6, verbose_name='top coordinate'),
        ),
        migrations.AddField(
            model_name='area',
            name='cached_effective_geometries',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (c3nav.api.schema.PolygonSchema | c3nav.api.schema.MultiPolygonSchema,)),))),
        ),
        migrations.AddField(
            model_name='space',
            name='cached_effective_geometries',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (c3nav.api.schema.PolygonSchema | c3nav.api.schema.MultiPolygonSchema,)),))),
        ),
        migrations.AddField(
            model_name='area',
            name='cached_bounds',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (c3nav.mapdata.models.geometry.base.CachedBounds, types.NoneType))),
        ),
        migrations.AddField(
            model_name='area',
            name='cached_points',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(tuple, (float, float)),)),))),
        ),
        migrations.AddField(
            model_name='space',
            name='cached_bounds',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (c3nav.mapdata.models.geometry.base.CachedBounds, types.NoneType))),
        ),
        migrations.AddField(
            model_name='space',
            name='cached_points',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(tuple, (float, float)),)),))),
        ),

        migrations.AddField(
            model_name='space',
            name='cached_simplified_geometries',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (c3nav.api.schema.PolygonSchema,)),))),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_bounds',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (django_pydantic_field.compat.django.GenericContainer(dict, (int, c3nav.mapdata.models.geometry.base.CachedBounds)), types.NoneType))),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_geometries',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (django_pydantic_field.compat.django.GenericContainer(dict, (int, django_pydantic_field.compat.django.GenericContainer(list, (c3nav.mapdata.models.locations.MaskedLocationTagGeometry | list[c3nav.mapdata.permissions.MapPermissionTaggedItem[c3nav.api.schema.PolygonSchema | c3nav.api.schema.MultiPolygonSchema | c3nav.api.schema.PointSchema]],)))), types.NoneType))),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_points',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(tuple, (int, float, float)),)),)),)), types.NoneType))),
        ),

        migrations.AlterModelOptions(
            name='dynamiclocation',
            options={'default_related_name': 'dynamic_location_tag_targets', 'verbose_name': 'Dynamic location tag target', 'verbose_name_plural': 'Dynamic location tag targets'},
        ),
        migrations.RemoveField(
            model_name='dynamiclocation',
            name='access_restriction',
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_all_position_secrets',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (str,))),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_all_static_targets',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(tuple, (str, int)),)),))),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='cached_target_subtitles',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(dict, (str, str)),)),))),
        ),
        migrations.RenameModel(
            old_name='DynamicLocation',
            new_name='DynamicLocationTagTarget',
        ),
        migrations.AddField(
            model_name='dynamiclocationtagtarget',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdata.specificlocation', related_name='dynamic_targets'),
        ),
        migrations.RunPython(make_dynamic_location_target_m2m, un_make_dynamic_location_m2m),
        migrations.RemoveField(
            model_name='specificlocation',
            name='dynamiclocations',
        ),
        migrations.AlterField(
            model_name='dynamiclocationtagtarget',
            name='position_secret',
            field=models.CharField(max_length=32, verbose_name='position secret'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='import_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='import tag'),
        ),
    ]
