# Generated by Django 5.1.5 on 2025-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0148_restructure_location_modeling_report'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locationslug',
            constraint=models.UniqueConstraint(condition=models.Q(('redirect', False)), fields=('group', 'specific'), name='unique_non_redirect_slugs'),
        ),
    ]
