# Generated by Django 5.1.5 on 2025-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0149_specificlocation_cached_describing_titles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='effective_bottom',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='bottom coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_left',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='left coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_right',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=6, verbose_name='right coordinate'),
        ),
        migrations.AddField(
            model_name='level',
            name='effective_top',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=6, verbose_name='top coordinate'),
        ),
        migrations.AlterField(
            model_name='mapupdatejob',
            name='job_type',
            field=models.CharField(choices=(('mapdata.recalculate_locationgroup_order', 'LocationGroup order'), ('mapdata.recalculate_specificlocation_order', 'SpecificLocation order'), ('mapdata.recalculate_specificlocation_cached_from_parents', 'SpecificLocation cached from parents'), ('mapdata.recalculate_geometries', 'geometries'), ('mapdata.recalculate_level_bounds', 'level bounds'), ('routing.rebuild_router', 'router'), ('routing.rebuild_locator', 'locator')), db_index=True, max_length=64),
        ),
    ]
