# Generated by Django 5.1.5 on 2025-04-08 16:49
import django.core.serializers.json
import django.db.models.functions.text
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models

import c3nav.mapdata.fields
import c3nav.mapdata.models.locations


def unmigrate_new_specific_locations(apps, model_name):
    SpecificLocation = apps.get_model('mapdata', 'SpecificLocation')

    # this needs to be here because https://code.djangoproject.com/ticket/36161
    SpecificLocation.objects.filter(import_tag="DELETEDELETEDELETE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0153_more_location_caching_and_dynamiclocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapupdatejob',
            name='job_type',
            field=models.CharField(choices=(('mapdata.evaluate_locationtag_relations', 'evaluate location relations'), ('mapdata.recalculate_locationtag_cached_from_parents', 'Location tag cached from parents'), ('mapdata.recalculate_locationtag_static_targets', 'Location tag static targets'), ('mapdata.recalculate_locationtag_dynamic_targets', 'Location tag dynamic targets'), ('mapdata.recalculate_locationtag_target_subtitles', 'Location tag target subtitles'), ('mapdata.recalculate_locationtag_minimum_access_restrictions', 'Location tag minimum access restrictions'), ('mapdata.recalculate_level_bounds', 'level bounds'), ('mapdata.recalculate_space_effective_geometries', 'Space effective geometries'), ('mapdata.recalculate_space_simplified_geometries', 'Space simplified geometries'), ('mapdata.recalculate_area_effective_geometries', 'Area effective geometries'), ('mapdata.recalculate_space_points', 'Space points'), ('mapdata.recalculate_area_points', 'Area points'), ('mapdata.recalculate_space_bounds', 'Space bounds'), ('mapdata.recalculate_area_bounds', 'Area bounds'), ('mapdata.recalculate_locationtag_geometries', 'Location tag geometries'), ('mapdata.recalculate_locationtag_bounds', 'Location tag bounds'), ('mapdata.recalculate_locationtag_points', 'Location tag points'), ('mapdata.recalculate_locationtag_final', 'Location tag finalize'), ('mapdata.recalculate_geometries', 'geometries'), ('routing.rebuild_router', 'router'), ('routing.rebuild_locator', 'locator')), db_index=True, max_length=64),
        ),
        migrations.RunPython(migrations.RunPython.noop, unmigrate_new_specific_locations),
        migrations.CreateModel(
            name='LocationTagAdjacency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mapdata.specificlocation')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapdata.specificlocation')),
            ],
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='can_report_missing',
            field=models.CharField(choices=[('dont_offer', "don't offer"), ('reject', 'offer in first step, then reject'), ('single', 'offer in first step, exclusive choice'), ('multiple', 'offer if nothing in the first step matches, multiple choice')], default='dont_offer', max_length=16, verbose_name='report missing location'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='can_report_mistake',
            field=models.CharField(choices=[('allow', 'allow'), ('reject', 'reject for all locations and sublocations')], default='allow', max_length=16, verbose_name='report mistakes'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='description',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='', help_text='to aid with selection in the report form', plural_name='descriptions', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='external_url_label',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='', plural_name='external_url_labels', verbose_name='external URL label'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='hierarchy',
            field=models.IntegerField(db_index=True, default=0, verbose_name='hierarchy'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='hub_import_type',
            field=models.CharField(blank=True, help_text='import hub locations of this type as children of this location', max_length=100, null=True, unique=True, verbose_name='hub import type'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='in_legend',
            field=models.BooleanField(default=False, verbose_name='show in legend (if color set)'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='load_group_contribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapdata.loadgroup', verbose_name='contribute to load group'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='report_help_text',
            field=c3nav.mapdata.fields.I18nField(blank=True, fallback_any=True, fallback_value='', help_text='to explain the report form or rejection', plural_name='report_help_texts', verbose_name='report help text'),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='mapdata.LocationTagAdjacency', to='mapdata.specificlocation', through_fields=("child", "parent")),
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='effective_minimum_access_restrictions',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=frozenset, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(frozenset, (int,))),
        ),
        migrations.AddField(
            model_name='report',
            name='created_parents',
            field=models.ManyToManyField(blank=True, help_text='select all that apply, if any', related_name='+', to='mapdata.specificlocation', verbose_name='location type'),
        ),
        migrations.AddField(
            model_name='themelocationgroupbackgroundcolor',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_colors', to='mapdata.specificlocation'),
        ),
        migrations.AlterField(
            model_name='themelocationgroupbackgroundcolor',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='mapdata.theme'),
        ),
        migrations.AddConstraint(
            model_name='LocationTagAdjacency',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_location_tag_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='LocationTagAdjacency',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='location_tag_parent_cant_be_child'),
        ),
        migrations.AlterModelOptions(
            name='specificlocation',
            options={'default_related_name': 'specific_locations', 'verbose_name': 'Specific Location', 'verbose_name_plural': 'Specific Locations'},
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='effective_order',
        ),
        migrations.AddField(
            model_name='specificlocation',
            name='include_in_random_location',
            field=models.BooleanField(default=False, verbose_name='include this and descendants with no children in random location feature'),
        ),

        migrations.AddField(
            model_name='altitudearea',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='altitudemarker',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='area',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='beaconmeasurement',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='building',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='column',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='dataoverlayfeature',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='door',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='hole',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='lineobstacle',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='poi',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='ramp',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='rangingbeacon',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='space',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.AddField(
            model_name='stair',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
    ]
