# Generated by Django 5.1.5 on 2025-04-09 14:47

import django.db.models.deletion
import django_pydantic_field.fields
import c3nav.mapdata.permissions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0155_new_location_hierarchy_migrate_data'),
        ('control', '0023_new_location_hierarchy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='only_one_slug_target',
        ),
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='unique_non_redirect_slugs',
        ),
        migrations.RemoveField(
            model_name='locationslug',
            name='group',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_groups',
        ),
        migrations.RemoveField(
            model_name='themelocationgroupbackgroundcolor',
            name='location_group',
        ),
        migrations.AlterField(
            model_name='locationslug',
            name='specific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_set', to='mapdata.specificlocation'),
        ),
        migrations.RenameModel(
            old_name='ThemeLocationGroupBackgroundColor',
            new_name='ThemeLocationTagColor',
        ),
        migrations.RenameField(
            model_name='locationslug',
            old_name='specific',
            new_name='target',
        ),
        migrations.AddConstraint(
            model_name='locationslug',
            constraint=models.UniqueConstraint(condition=models.Q(('redirect', False)), fields=('target',),
                                               name='unique_non_redirect_slugs'),
        ),
        migrations.RemoveField(
            model_name='area',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='space',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='access_restriction',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='label_settings',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='groups',
        ),
        migrations.DeleteModel(
            name='LocationGroupCategory',
        ),
        migrations.DeleteModel(
            name='LocationGroup',
        ),
        migrations.RenameModel(
            old_name='SpecificLocation',
            new_name='LocationTag',
        ),
        migrations.AlterModelOptions(
            name='locationtag',
            options={'default_related_name': 'location_tags', 'verbose_name': 'Location Tag', 'verbose_name_plural': 'Location Tags'},
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='import_block_geom',
        ),
        migrations.RenameField(
            model_name='locationtag',
            old_name='import_block_data',
            new_name='import_block',
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.RenameField(
            model_name='report',
            old_name='location',
            new_name='location_tag',
        ),
        migrations.AlterField(
            model_name='report',
            name='location_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports',
                                    to='mapdata.locationtag', verbose_name='location tag'),
        ),
        migrations.CreateModel(
            name='LocationTagInheritedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (str,)),)))),
                ('label_settings_id', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (int,)),)))),
                ('external_url_label', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(dict, (str, str)),)),)))),
                ('describing_title', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(dict, (str, str)),)),)))),
                ('colors', django_pydantic_field.fields.PydanticSchemaField(config=None, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(dict, (int, django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (c3nav.mapdata.models.locations.FillAndBorderColor,)),)))))),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapdata.locationtag')),
                ('ancestors', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (int,)),)))),
                ('ancestor_paths', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(list, (int,)),)),)))),
                ('descendants', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (int,)),)))),
                ('descendant_paths', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (django_pydantic_field.compat.django.GenericContainer(list, (int,)),)),)))),
            ],
            options={
                'verbose_name': 'Location Tag Inherited Values',
                'verbose_name_plural': 'Location Tags Inherited Values',
            },
        ),
        migrations.CreateModel(
            name='LocationTagEffectiveAccessRestrictionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_restrictions', models.ManyToManyField(related_name='+', to='mapdata.accessrestriction')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                          related_name='inherited', to='mapdata.locationtag')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTagTargetInheritedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(c3nav.mapdata.permissions.MapPermissionTaggedItem, (int,)),)))),
                ('area', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited', to='mapdata.area')),
                ('level', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited', to='mapdata.level')),
                ('poi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited', to='mapdata.poi')),
                ('space', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited', to='mapdata.space')),
            ],
            options={
                'verbose_name': 'Location Tag Target Inherited Values',
                'verbose_name_plural': 'Location Tag Targets Inherited Values',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', True), ('level__isnull', False), ('poi__isnull', True), ('space__isnull', True)), models.Q(('area__isnull', True), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', False)), models.Q(('area__isnull', False), ('level__isnull', True), ('poi__isnull', True), ('space__isnull', True)), models.Q(('area__isnull', True), ('level__isnull', True), ('poi__isnull', False), ('space__isnull', True)), _connector='OR'), name='target_inherited_values_has_unique_target')],
            },
        ),
    ]
