# Generated by Django 5.2 on 2025-09-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0139_space_media_panel_done_alter_rangingbeacon_addresses'),
        ('mapdata', '0156_new_location_hierarchy_cleanup'),
    ]

    operations = [
    ]
