# Generated by Django 5.1.5 on 2025-04-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0159_new_location_hierarchymigrate_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='only_one_slug_target',
        ),
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='unique_non_redirect_slugs',
        ),
        migrations.RemoveField(
            model_name='locationslug',
            name='group',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_groups',
        ),
        migrations.RemoveField(
            model_name='themelocationgroupbackgroundcolor',
            name='location_group',
        ),
        migrations.AlterField(
            model_name='locationslug',
            name='specific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_set', to='mapdata.specificlocation'),
        ),
        migrations.RenameModel(
            old_name='ThemeLocationGroupBackgroundColor',
            new_name='ThemeLocationBackgroundColor',
        ),
        migrations.RenameField(
            model_name='locationslug',
            old_name='specific',
            new_name='target',
        ),
        migrations.AddConstraint(
            model_name='locationslug',
            constraint=models.UniqueConstraint(condition=models.Q(('redirect', False)), fields=('target',),
                                               name='unique_non_redirect_slugs'),
        ),
        migrations.AddField(
            model_name='locationancestry',
            name='first_parentages',
            field=models.ManyToManyField(related_name='provides_ancestries', through='mapdata.LocationAncestryPath',
                                         to='mapdata.locationparentage'),
        ),
        migrations.RemoveField(
            model_name='area',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='space',
            name='load_group_contribute',
        ),
    ]
