# Generated by Django 5.1.5 on 2025-04-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0159_new_location_hierarchymigrate_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='only_one_slug_target',
        ),
        migrations.RemoveConstraint(
            model_name='locationslug',
            name='unique_non_redirect_slugs',
        ),
        migrations.RemoveField(
            model_name='locationslug',
            name='group',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_groups',
        ),
        migrations.RemoveField(
            model_name='themelocationgroupbackgroundcolor',
            name='location_group',
        ),
        migrations.AlterField(
            model_name='locationslug',
            name='specific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_set', to='mapdata.specificlocation'),
        ),
        migrations.RenameModel(
            old_name='ThemeLocationGroupBackgroundColor',
            new_name='ThemeLocationTagColor',
        ),
        migrations.RenameField(
            model_name='locationslug',
            old_name='specific',
            new_name='target',
        ),
        migrations.AddConstraint(
            model_name='locationslug',
            constraint=models.UniqueConstraint(condition=models.Q(('redirect', False)), fields=('target',),
                                               name='unique_non_redirect_slugs'),
        ),
        migrations.RemoveField(
            model_name='area',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='space',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='access_restriction',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='label_settings',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='load_group_contribute',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='groups',
        ),
        migrations.DeleteModel(
            name='LocationGroupCategory',
        ),
        migrations.DeleteModel(
            name='LocationGroup',
        ),
        migrations.RenameModel(
            old_name='SpecificLocation',
            new_name='LocationTag',
        ),
        migrations.AlterModelOptions(
            name='locationtag',
            options={'default_related_name': 'location_tags', 'verbose_name': 'Location Tag', 'verbose_name_plural': 'Location Tags'},
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='import_block_geom',
        ),
        migrations.RenameField(
            model_name='locationtag',
            old_name='import_block_data',
            new_name='import_block',
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='import_block',
            field=models.BooleanField(default=False, verbose_name="don't change on import"),
        ),
        migrations.RenameField(
            model_name='report',
            old_name='location',
            new_name='location_tag',
        ),
        migrations.AlterField(
            model_name='report',
            name='location_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports',
                                    to='mapdata.locationtag', verbose_name='location tag'),
        ),
    ]
