# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('review_changesets', models.BooleanField(default=False, verbose_name='can review changesets')),
                ('direct_edit', models.BooleanField(default=False, verbose_name='can activate direct editing')),
                ('control_panel', models.BooleanField(default=False, verbose_name='can access control panel')),
                ('grant_permissions', models.BooleanField(default=False, verbose_name='can grant control permissions')),
                ('manage_announcements', models.BooleanField(default=False, verbose_name='manage announcements')),
            ],
            options={
                'verbose_name': 'User Permissions',
                'verbose_name_plural': 'User Permissions',
                'default_related_name': 'permissions',
            },
        ),
    ]
