# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20161220_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='expipres',
            new_name='expires',
        ),
        migrations.RenameField(
            model_name='accesstokeninstance',
            old_name='expipres',
            new_name='expires',
        ),
        migrations.AlterField(
            model_name='accessuser',
            name='user_url',
            field=models.CharField(help_text='Usually an URL to a profile somewhere', max_length=200, unique=True, verbose_name='access name'),
        ),
    ]
