# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_userpermissions_access_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='access_all',
            field=models.BooleanField(default=False, verbose_name='can grant access to everything'),
        ),
    ]
