# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20161220_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoperator',
            name='can_award_permissions',
            field=models.CharField(max_length=2048, verbose_name='can award permissions'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='permissions',
            field=models.CharField(max_length=2048, verbose_name='permissions'),
        ),
    ]
