# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20171210_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissions',
            old_name='access_all',
            new_name='grant_all_access',
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='api_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='API secret'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='max_changeset_changes',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='max changes per changeset'),
        ),
    ]
