# Generated by Django 2.1.1 on 2018-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_more_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='base_mapdata_access',
            field=models.BooleanField(default=False, verbose_name='can always access base map data'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='editor_access',
            field=models.BooleanField(default=False, verbose_name='can always access editor'),
        ),
    ]
