# Generated by Django 2.1.4 on 2018-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_user_space_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='manage_map_updates',
            field=models.BooleanField(default=False, verbose_name='manage map updates'),
        ),
    ]
