# Generated by Django 4.2.1 on 2023-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0009_django_4_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="mesh_control",
            field=models.BooleanField(
                default=False, verbose_name="can access mesh control"
            ),
        ),
    ]
