# Generated by Django 4.2.3 on 2023-12-01 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0010_userpermissions_mesh_control"),
        ("api", "0003_rename_token_logintoken_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermissions",
            name="api_secret",
        ),
    ]
