# Generated by Django 4.2.7 on 2023-12-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0011_remove_userpermissions_api_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="grant_unlimited_access",
            field=models.BooleanField(
                default=False, verbose_name="grant unlimited access"
            ),
        ),
    ]
