# Generated by Django 5.0.3 on 2024-08-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0013_userpermissions_nonpublic_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="sources_access",
            field=models.BooleanField(
                default=False, verbose_name="can access sources in editor"
            ),
        ),
    ]
