# Generated by Django 5.0.8 on 2024-12-24 17:36

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_remove_userpermissions_control_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='quests',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (str,))),
        ),
    ]
