# Generated by Django 5.0.8 on 2024-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_userpermissions_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='impolite_quests',
            field=models.BooleanField(default=False, verbose_name='dont say thanks after completing a quest'),
        ),
    ]
