# Generated by Django 5.0.8 on 2024-12-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_userpermissions_impolite_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='passive_ap_name_scanning',
            field=models.BooleanField(default=False, verbose_name='passive ap name scanning'),
        ),
    ]
