# Generated by Django 5.0.8 on 2024-12-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_userpermissions_passive_ap_name_scanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='can_write_load_data',
            field=models.BooleanField(default=False, verbose_name='write load data'),
        ),
    ]
