# Generated by Django 6.0 on 2025-12-24 11:43

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_userpermissions_can_write_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='passive_scan_collection',
            field=models.BooleanField(default=False, verbose_name='collect all locate wifi scans'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='quests',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (str,))),
        ),
    ]
