# Generated by Django 5.1.5 on 2025-01-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # this is for sqlite… remove constraints so the rest won't fail

    dependencies = [
        ('control', '0020_userpermissions_can_write_load_data'),
        ('mapdata', '0138_rangingbeacon_max_observed_num_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='review_group_reports',
            field=models.ManyToManyField(blank=True, limit_choices_to={'access_restriction': None}, to='mapdata.locationgroup', verbose_name='can review reports belonging to', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='userspaceaccess',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdata.space', db_constraint=False),
        ),
    ]