# Generated by Django 5.1.5 on 2025-01-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_prepare_userpermissions_restructured_locations'),
        ('mapdata', '0144_remove_location_multi_table_inheritance_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='review_group_reports',
            field=models.ManyToManyField(blank=True, limit_choices_to={'access_restriction': None}, to='mapdata.locationgroup', verbose_name='can review reports belonging to'),
        ),
        migrations.AlterField(
            model_name='userspaceaccess',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdata.space'),
        ),
    ]
