# Generated by Django 5.1.5 on 2025-04-09 12:03

from django.db import migrations, models


def migrate_location_hierarchy(apps, model_name):
    UserPermissions = apps.get_model('control', 'UserPermissions')

    # migrate userpermissions locationgroup reference
    for user_permissions in UserPermissions.objects.prefetch_related("review_group_reports"):
        user_permissions.review_child_reports.set([group.id for group in user_permissions.review_group_reports.all()])


def unmigrate_location_hierarchy(apps, model_name):
    UserPermissions = apps.get_model('control', 'UserPermissions')

    # migrate userpermissions locationgroup reference
    for user_permissions in UserPermissions.objects.prefetch_related("review_child_reports"):
        user_permissions.review_group_reports.set(
            [group.id for group in user_permissions.review_child_reports.all()]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_alter_userpermissions_restructured_locations'),
        ('mapdata', '0159_new_location_hierarchy_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='review_child_reports',
            field=models.ManyToManyField(blank=True, limit_choices_to={'access_restriction': None}, to='mapdata.specificlocation', verbose_name='can review reports belonging to'),
        ),
        migrations.RunPython(migrate_location_hierarchy, unmigrate_location_hierarchy),
        migrations.RemoveField(
            model_name='userpermissions',
            name='review_group_reports',
        ),
    ]
