# Generated by Django 2.1.1 on 2018-11-23 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='secret')),
                ('session_auth_hash', models.CharField(max_length=128, verbose_name='session auth hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login tokens',
                'verbose_name_plural': 'login tokens',
                'default_related_name': 'login_tokens',
            },
        ),
    ]
