# Generated by Django 5.0.8 on 2024-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_secret_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='scope_load',
            field=models.BooleanField(default=False, verbose_name='load write access'),
        ),
    ]
